######################################################################
##
## Filename: s6base_tb.udo
## Created on: Mon Nov 09 15:13:16 Hora padrão de GMT 2020
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
run -all