######################################################################
##
## Filename: interpol4x.udo
## Created on: Wed Nov 28 17:39:08 Hora padrão de GMT 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
