######################################################################
##
## Filename: s6base_tb.udo
## Created on: Wed Oct 30 17:24:29 GMT Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
run -all